---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterblock-csi-pv
  annotations:
    storageClassName: glusterblock-csi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
