---
name: build-test
on:
  push:
    branches:
      - 'main'
      - 'release-**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
      - name: unit tests
        run: go test ./... -race -v
      - name: Test build
        run: CGO_ENABLED=0 go build -trimpath ./cmd/glusterfs
